2023-12-15 20:42:21.071 ERROR (MainThread) [homeassistant.setup] Setup failed for 'xiaomi_miot': Integration not found.
2023-12-15 20:42:22.608 WARNING (SyncWorker_4) [miio.device] Found an unsupported model 'lumi.gateway.mgl001' for class 'Gateway'. If this is working for you, please open an issue at https://github.com/rytilahti/python-miio/
2023-12-15 20:42:22.883 ERROR (MainThread) [homeassistant.components.weather] Platform met does not generate unique IDs. ID home already exists - ignoring weather.forecast_home_assistant
2023-12-15 20:42:33.100 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform xiaomi_miio is taking over 10 seconds.
2023-12-15 20:42:33.101 WARNING (MainThread) [homeassistant.components.light] Setup of light platform xiaomi_miio is taking over 10 seconds.
2023-12-15 20:42:39.316 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:42:39.319 ERROR (MainThread) [homeassistant.components.light] xiaomi_miio: Error on device update!
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise RecoverableError(error)
miio.exceptions.RecoverableError: {'code': -9999, 'message': 'user ack timeout'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise RecoverableError(error)
miio.exceptions.RecoverableError: {'code': -9999, 'message': 'user ack timeout'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise RecoverableError(error)
miio.exceptions.RecoverableError: {'code': -9999, 'message': 'user ack timeout'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 214, in send
    self._handle_error(payload["error"])
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 274, in _handle_error
    raise RecoverableError(error)
miio.exceptions.RecoverableError: {'code': -9999, 'message': 'user ack timeout'}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 575, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/components/xiaomi_miio/light.py", line 1029, in async_update
    state_dict = await self.hass.async_add_executor_job(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/gateway/light.py", line 39, in rgb_status
    state_int = self._gateway.send("get_rgb").pop()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 248, in send
    return self.send(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 248, in send
    return self.send(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 248, in send
    return self.send(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 256, in send
    raise DeviceException("Unable to recover failed command") from ex
miio.exceptions.DeviceException: Unable to recover failed command
2023-12-15 20:42:39.339 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:42:57.178 ERROR (MainThread) [homeassistant.components.weather] Platform met does not generate unique IDs. ID home already exists - ignoring weather.forecast_home_assistant
2023-12-15 20:42:59.926 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703640640320] Error handling message: Unknown error (unknown_error) relizerel161 from 192.168.1.67 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 707, in websocket_get_translations
    resources = await async_get_translations(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 320, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 211, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 232, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'xiaomi_miot' not found.
2023-12-15 20:43:03.104 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:43:09.418 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:43:19.342 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:43:25.477 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:43:33.104 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:43:39.346 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:43:49.342 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:43:55.473 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:43:58.137 WARNING (MainThread) [xiaomi_ble.parser] Decryption failed: 
2023-12-15 20:44:03.106 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:44:09.320 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:44:19.342 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:44:25.501 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:44:33.107 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:44:39.307 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:44:49.344 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:44:55.497 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:45:03.107 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:45:09.439 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:45:19.344 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:45:25.586 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:45:33.107 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:45:39.307 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:45:49.346 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:45:55.486 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:46:03.108 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:46:09.338 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:46:19.347 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:46:25.465 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:46:33.108 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:46:39.200 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:46:49.348 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:46:55.460 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:47:03.109 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:47:09.217 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:47:19.349 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:47:25.557 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:47:33.110 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:47:39.441 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:47:49.350 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:47:55.603 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:48:03.112 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:48:09.298 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:48:19.350 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:48:25.537 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:48:33.111 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:48:39.297 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:48:49.351 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:48:55.613 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:49:03.112 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:49:09.335 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:49:19.352 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:49:25.615 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:49:33.113 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:49:39.287 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:49:49.355 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:49:55.577 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:50:03.115 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:50:09.352 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:50:19.354 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:50:25.557 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:50:33.114 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:50:39.343 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:50:49.354 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:50:55.578 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:51:03.115 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:51:09.278 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:51:19.355 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:51:25.578 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:51:33.117 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:51:39.380 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:51:49.356 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:51:55.632 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:52:03.118 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:52:09.253 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:52:19.357 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:52:25.637 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:52:33.118 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:52:39.255 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:52:49.357 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:52:55.538 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:53:03.119 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:53:09.317 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:53:19.357 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:53:25.541 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:53:33.119 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:53:39.397 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:53:49.357 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:53:55.677 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:54:03.120 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:54:09.297 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:54:19.358 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:54:25.498 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:54:33.121 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:54:40.237 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:54:49.358 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:54:55.552 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:55:03.121 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:55:09.417 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:55:19.359 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:55:25.697 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:55:33.123 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:55:39.365 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:55:49.360 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:55:55.560 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:56:03.124 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:56:09.287 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:56:19.360 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:56:25.676 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:56:33.125 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:56:39.367 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:56:49.362 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:56:56.416 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:57:03.124 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:57:09.289 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:57:19.362 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:57:25.569 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:57:33.125 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:57:39.317 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:57:49.363 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:57:55.470 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:58:03.126 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:58:09.334 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:58:19.364 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:58:24.989 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703608165952] Error handling message: Unknown error (unknown_error) relizerel161 from 192.168.1.67 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 707, in websocket_get_translations
    resources = await async_get_translations(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 320, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 211, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 232, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'xiaomi_miot' not found.
2023-12-15 20:58:25.583 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:58:33.126 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:58:39.297 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:58:49.364 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:58:55.477 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:59:03.129 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:59:09.317 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:59:19.365 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:59:25.514 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:59:33.128 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 20:59:39.255 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 20:59:49.366 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 20:59:55.615 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:00:03.130 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:00:09.314 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:00:19.368 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:00:25.588 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:00:33.130 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:00:39.374 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:00:49.369 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:00:55.633 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:01:03.131 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:01:09.334 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:01:13.198 ERROR (MainThread) [homeassistant.components.hassio] Failed to to call /store/repositories - https://github.com/al-one/hass-xiaomi-miot is not a valid add-on repository
2023-12-15 21:01:19.370 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:01:25.597 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:01:33.131 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:01:39.397 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:01:49.371 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:01:55.495 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:02:03.132 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:02:09.459 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:02:19.372 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:02:25.704 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:02:33.133 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:02:39.325 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:02:49.373 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:02:55.503 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:03:03.133 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:03:09.212 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:03:19.374 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:03:25.610 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:03:33.133 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:03:39.334 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:03:49.375 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:03:56.571 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:04:03.135 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:04:09.361 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:04:19.375 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:04:25.651 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:04:33.135 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:04:39.236 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:04:49.376 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:04:55.618 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:05:03.136 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:05:09.238 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:05:19.376 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:05:25.470 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:05:33.137 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:05:39.490 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:05:49.377 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:05:55.624 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:06:03.137 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:06:09.347 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:06:19.377 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:06:25.628 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:06:33.138 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:06:39.275 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:06:49.379 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:06:55.528 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:07:03.139 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:07:09.209 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:07:19.380 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:07:25.509 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:07:33.140 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:07:39.310 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:07:49.381 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:07:55.538 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:08:03.140 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:08:09.258 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:08:19.381 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:08:25.589 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:08:33.142 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:08:39.390 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:08:49.382 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:08:55.646 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:09:03.141 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:09:09.249 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:09:19.382 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:09:25.587 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:09:33.142 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:09:39.248 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:09:49.383 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:09:55.668 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:10:03.143 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:10:09.543 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:10:19.384 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:10:25.553 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:10:33.142 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:10:39.247 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:10:49.384 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:10:55.659 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:11:03.144 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:11:09.409 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:11:19.385 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:11:25.662 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:11:33.144 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:11:43.182 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:11:49.386 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:11:55.562 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:12:03.146 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:12:09.347 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:12:19.386 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:12:25.673 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:12:33.147 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:12:39.306 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:12:49.387 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:12:55.570 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:13:03.147 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:13:10.232 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: timed out
2023-12-15 21:13:19.387 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:13:25.806 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:13:33.148 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:13:39.294 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:13:49.389 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:13:55.486 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:14:03.150 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:14:09.266 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:14:19.389 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:14:25.465 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:14:33.149 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:14:39.286 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:14:49.390 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:14:55.606 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:15:03.150 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:15:09.325 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:15:19.392 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:15:25.586 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:15:33.151 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:15:39.246 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:15:49.393 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:15:55.465 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:16:03.150 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:16:09.311 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:16:19.394 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:16:25.526 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:16:33.151 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:16:39.317 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:16:49.394 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:16:55.525 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:17:03.151 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:17:09.403 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:17:19.396 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:17:25.805 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:17:33.152 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:17:39.235 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:17:49.397 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:17:55.634 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:18:03.152 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:18:10.464 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:18:19.398 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:18:25.521 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:18:33.153 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:18:39.337 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:18:49.400 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:18:55.733 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:19:03.153 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:19:09.332 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:19:19.400 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:19:25.620 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:19:33.155 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:19:39.336 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:19:49.402 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:19:55.517 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:20:03.157 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:20:09.252 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:20:19.402 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:20:25.725 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:20:33.157 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:20:39.372 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:20:49.403 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:20:55.542 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:21:03.158 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:21:09.304 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:21:19.404 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:21:25.730 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:21:33.160 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:21:39.241 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:21:49.405 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:21:55.530 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:22:03.161 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:22:09.301 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:22:19.405 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:22:25.502 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:22:33.161 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:22:39.281 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:22:49.406 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:22:55.554 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:23:03.162 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:23:09.301 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:23:19.406 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:23:25.542 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:23:33.163 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:23:39.362 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:23:49.408 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:23:55.570 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:24:03.164 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:24:09.310 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:24:19.408 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:24:25.645 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:24:33.164 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:24:39.420 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:24:42.712 ERROR (MainThread) [homeassistant.components.github] An error occurred while processing new events - Bad credentials
2023-12-15 21:24:49.410 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:24:55.753 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:25:03.166 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:25:09.261 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:25:19.413 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:25:25.656 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:25:33.165 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:25:40.381 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:25:49.412 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:25:55.555 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:26:03.166 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:26:09.365 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:26:19.413 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:26:25.559 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:26:33.168 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:26:39.383 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:26:49.413 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:26:55.664 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:27:03.168 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:27:09.402 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:27:19.415 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:27:25.518 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:27:33.169 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:27:39.398 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:27:49.416 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:27:55.568 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:28:03.170 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:28:09.393 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:28:19.416 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:28:25.500 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:28:33.170 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:28:39.322 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:28:49.418 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:28:55.576 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:29:03.172 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:29:09.369 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:29:19.417 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:29:25.682 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:29:33.172 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:29:39.357 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:29:49.419 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:29:55.537 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:30:03.172 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:30:09.440 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:30:19.419 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:30:25.537 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:30:33.175 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:30:39.492 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:30:49.420 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:30:55.718 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:31:03.175 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:31:09.297 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:31:19.420 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:31:25.592 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:31:33.175 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:31:39.416 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:31:49.421 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:31:55.800 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:32:03.176 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:32:09.277 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:32:19.423 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:32:25.597 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:32:33.176 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:32:39.276 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:32:49.423 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:32:55.535 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:33:03.177 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:33:09.275 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:33:19.426 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:33:27.277 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:33:33.179 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:33:39.317 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:33:49.425 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:33:55.613 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:34:03.179 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:34:09.355 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:34:19.427 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:34:25.642 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:34:33.179 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:34:39.256 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:34:49.426 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:34:56.675 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:35:03.180 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:35:09.337 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:35:19.427 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:35:25.677 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:35:33.181 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:35:39.294 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:35:49.429 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:35:55.734 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:36:03.182 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:36:09.415 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:36:19.430 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:36:25.534 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:36:33.183 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:36:39.254 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:36:49.429 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:36:55.629 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:37:03.184 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:37:09.293 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:37:19.431 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:37:25.533 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:37:33.184 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:37:39.293 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:37:49.432 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:37:55.635 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:38:03.184 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:38:09.358 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:38:19.432 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:38:25.513 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:38:33.185 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:38:40.313 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:38:49.433 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:38:55.513 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:39:03.188 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:39:09.292 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:39:19.434 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:39:25.893 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:39:33.188 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:39:39.294 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:39:49.435 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:39:55.648 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:40:03.188 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:40:09.612 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:40:19.435 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:40:25.533 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:40:33.190 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:40:39.272 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:40:49.437 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:40:55.532 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:41:03.189 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:41:09.273 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:41:19.437 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:41:25.531 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:41:33.191 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:41:39.271 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:41:49.437 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:41:55.711 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:42:03.191 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:42:09.330 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:42:19.438 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:42:25.531 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:42:33.191 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:42:39.293 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:42:49.438 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:42:55.571 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:43:03.191 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:43:09.330 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:43:19.439 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:43:25.690 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:43:33.192 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:43:39.293 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:43:49.441 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:43:55.509 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:44:03.194 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:44:09.310 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:44:19.441 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:44:25.561 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:44:33.194 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:44:39.289 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:44:49.441 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:44:55.683 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:45:03.195 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:45:09.330 ERROR (SyncWorker_6) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:45:19.443 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:45:25.609 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:45:33.196 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:45:39.548 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:45:49.443 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:45:55.549 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:46:03.197 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:46:09.319 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:46:19.444 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:46:25.570 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:46:33.197 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:46:38.187 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703595314240] Error handling message: Unknown error (unknown_error) relizerel161 from 192.168.1.67 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 707, in websocket_get_translations
    resources = await async_get_translations(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 320, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 211, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 232, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'xiaomi_miot' not found.
2023-12-15 21:46:39.333 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:46:49.445 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:46:55.549 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:47:03.201 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:47:09.368 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:47:19.446 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:47:25.568 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:47:33.200 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:47:39.289 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:47:49.447 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:47:56.635 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:48:03.201 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:48:09.312 ERROR (SyncWorker_14) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:48:19.447 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:48:21.636 ERROR (MainThread) [homeassistant.components.homeassistant]   in "/config/configuration.yaml", line 12, column 12: Unable to read file /config/customize.yaml.
2023-12-15 21:48:25.628 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:48:33.202 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:48:39.492 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:48:49.449 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:48:55.792 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:49:03.202 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:49:09.396 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:49:19.448 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:49:25.567 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:49:33.203 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:49:39.330 ERROR (SyncWorker_11) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:49:49.450 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:49:55.566 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:50:03.204 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:50:09.367 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:50:19.450 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:50:25.546 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:50:33.205 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:50:39.306 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:50:49.450 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:50:55.587 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:51:03.204 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:51:09.368 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:51:19.452 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:51:25.727 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:51:33.206 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:51:39.308 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:51:49.453 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:51:55.730 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:52:03.205 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:52:09.349 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:52:19.455 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:52:25.630 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:52:33.206 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:52:39.487 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:52:49.457 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:52:51.542 ERROR (MainThread) [homeassistant.components.homeassistant] The system cannot reload because the configuration is not valid: Error loading /config/configuration.yaml:   in "/config/configuration.yaml", line 12, column 12: Unable to read file /config/customize.yaml.
2023-12-15 21:52:51.543 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703674223808] Cannot quick reload all YAML configurations because the configuration is not valid: Error loading /config/configuration.yaml:   in "/config/configuration.yaml", line 12, column 12: Unable to read file /config/customize.yaml.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 986, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/homeassistant/__init__.py", line 342, in async_handle_reload_all
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Cannot quick reload all YAML configurations because the configuration is not valid: Error loading /config/configuration.yaml:   in "/config/configuration.yaml", line 12, column 12: Unable to read file /config/customize.yaml.
2023-12-15 21:52:55.635 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:53:03.207 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:53:09.405 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:53:19.456 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:53:25.535 ERROR (SyncWorker_9) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:53:33.207 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:53:39.358 ERROR (SyncWorker_7) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:53:49.457 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:53:55.546 ERROR (SyncWorker_3) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:53:56.184 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Service not found for call_service at pos 1: Service shell_command.update_xiaomi_miot not found.
2023-12-15 21:53:56.185 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703595999168] Error handling message: Service shell_command.update_xiaomi_miot not found. (home_assistant_error) relizerel161 from 192.168.1.67 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
2023-12-15 21:54:03.207 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:54:09.291 ERROR (SyncWorker_1) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:54:19.458 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:54:25.747 ERROR (SyncWorker_13) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:54:33.209 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:54:39.385 ERROR (SyncWorker_5) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:54:49.458 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:54:50.348 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139703574925120] Error handling message: Unknown error (unknown_error) relizerel161 from 192.168.1.67 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 707, in websocket_get_translations
    resources = await async_get_translations(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 320, in async_get_translations
    cached = await cache.async_fetch(language, category, components)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 211, in async_fetch
    await self._async_load(language, components_to_load)
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 232, in _async_load
    raise int_or_exc
homeassistant.loader.IntegrationNotFound: Integration 'hacs' not found.
2023-12-15 21:54:55.765 ERROR (SyncWorker_0) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:55:03.209 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:55:09.364 ERROR (SyncWorker_12) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:55:19.458 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:55:25.588 ERROR (SyncWorker_8) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:55:33.210 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:55:39.339 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:55:49.460 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:55:55.564 ERROR (SyncWorker_10) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:56:03.211 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:56:09.377 ERROR (SyncWorker_2) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:56:19.461 WARNING (MainThread) [homeassistant.helpers.entity] Update of alarm_control_panel.xiaomi_smart_home_hub_2_alarm is taking over 10 seconds
2023-12-15 21:56:25.684 ERROR (SyncWorker_4) [miio.miioprotocol] Got error when receiving: {'code': -9999, 'message': 'user ack timeout'}
2023-12-15 21:56:33.211 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.xiaomi_smart_home_hub_2_illuminance is taking over 10 seconds
2023-12-15 21:56:34.742 WARNING (MainThread) [homeassistant.core] Task <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.11/asyncio/futures.py:387, <1 more>, Task.task_wakeup()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2023-12-15 21:56:34.742 WARNING (MainThread) [homeassistant.core] Task <Task pending name='track time interval 0:00:30' coro=<EntityPlatform._update_entity_states() running at /usr/src/homeassistant/homeassistant/helpers/entity_platform.py:877> wait_for=<Future cancelled> cb=[set.remove()]> was still running after stage 2 shutdown; Integrations should cancel non-critical tasks when receiving the stop event to prevent delaying shutdown
2023-12-15 21:56:34.815 WARNING (Thread-3 (_do_shutdown)) [homeassistant.util.executor] Thread[SyncWorker_14] is still running at shutdown: File "/usr/local/lib/python3.11/threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 83, in _worker
    work_item.run()
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.11/site-packages/miio/click_common.py", line 184, in _wrap
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/miio/gateway/gateway.py", line 408, in get_illumination
    return self.send("get_illumination").pop()
  File "/usr/local/lib/python3.11/site-packages/miio/device.py", line 107, in send
    return self._protocol.send(
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 248, in send
    return self.send(
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 248, in send
    return self.send(
  File "/usr/local/lib/python3.11/site-packages/miio/miioprotocol.py", line 193, in send
    data, addr = s.recvfrom(4096)
